name: Feature Request
description: Suggest an idea for this project (English Template)
labels: [ "enhancement" ]
body:
  - type: checkboxes
    id: pre-check
    attributes:
      label: Before requesting...
      options:
        - label: Example Mod is up to date (Latest GitHub Action Build)
        - label: Similar issues don't exist in the issue tracker
          required: true
  - type: textarea
    id: reason
    attributes:
      label: Reason
      description: Why do you want this feature? What problem do you want to solve? How can the suggested feature help with that?
      placeholder: Tell us what you want!
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: Describe the feature you want, as detailed as possible
      placeholder: I want to see a fancy starry sky when I look up at midnight.
    validations:
      required: true
  - type: textarea
    id: other-information
    attributes:
      label: Other information
      description: Other useful information to this feature request. Leave empty if there is none.
