name: 功能请求
description: 请求一个功能
labels: [ "enhancement" ]
body:
  - type: checkboxes
    id: pre-check
    attributes:
      label: 在请求功能之前，请确保您已经完成以下检查：
      options:
        - label: Example Mod 是最新的构建版
        - label: 问题追踪器中没有类似的功能请求
          required: true
  - type: textarea
    id: reason
    attributes:
      label: 原因
      description: 为什么要请求这个功能？你想解决什么问题？
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 功能描述
      description: 请尽可能包含更多描述。
      placeholder: 苦力怕爆炸崩游戏
    validations:
      required: true
  - type: textarea
    id: other-information
    attributes:
      label: 其他信息
      description: 其他对这个功能有用的信息。
