plugins {
    id "com.github.johnrengelman.shadow" version "8.1.1"
}

architectury {
    platformSetupLoomIde()
    forge()
}

def generatedResources = file("src/generated")

sourceSets {
    main {
        resources.srcDir generatedResources
    }
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath

    forge {
//        mixinConfig "sparklib.mixins.json"
        mixinConfig "testmod.mixins.json"
    }

    runs {
        data {
            data()
            programArgs "--all", "--mod", "testmod"
            programArgs "--output", generatedResources.absolutePath

//            property "forge.logging.markers", "SCAN,REGISTRIES,REGISTRYDUMP"
        }
    }
}

configurations {
    common
    shadowCommon // Don't use shadow from the shadow plugin since it *excludes* files.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
}

dependencies {
    forge "net.minecraftforge:forge:${rootProject.minecraft_version}-${rootProject.forge_version}"
    // Remove the next line if you don't want to depend on the API
    modImplementation "dev.architectury:architectury-forge:${rootProject.architectury_version}"

    implementation project(path: ":forge", configuration: "namedElements")

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    common(project(path: ":testmod-common", configuration: "namedElements")) { transitive false }

//    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:${rootProject.mixinextras_version}"))
//    implementation(include("io.github.llamalad7:mixinextras-forge:${rootProject.mixinextras_version}"))

    // fix runtime NoClassDefError
    forgeRuntimeLibrary "com.github.erha134:EasyLib:${rootProject.easylib_version}"
    forgeRuntimeLibrary "com.github.erha134.SparkConfig:sparkconfig-core:${rootProject.sparkconfig_version}"
    forgeRuntimeLibrary "com.github.erha134.SparkConfig:sparkconfig-serializers-gson:${rootProject.sparkconfig_version}"
}
